import type { EnrichedProvider, CategoryGroup, Metric } from "./types"

const MASTER_REGISTRY = [
  {
    id: "1",
    name: "RETS NSW",
    website: "https://retsnsw.edu.au",
    website_secondary: "https://retsnsw.edu.au/courses/cpp41419",
    state: "NSW",
    type: "Private",
    price: 1450,
    mdpa_score: 91,
    status: "active",
    phone: "02 8007 4544",
    email: null,
    rto_code: "",
    operational_pattern: "Operational Continuity Profile",
    network_id: "NET-PHOENIX-01",
  },
  {
    id: "2",
    name: "Kaplan Professional",
    website: "https://www.kaplanprofessional.edu.au",
    website_secondary: "https://www.kaplanprofessional.edu.au/courses/real-estate",
    state: "Multi",
    type: "Private",
    price: 1800,
    mdpa_score: 90,
    status: "active",
    phone: null,
    email: null,
    rto_code: "31403",
    operational_pattern: "Operational Continuity Profile",
    network_id: "NET-PHOENIX-01",
  },
  {
    id: "3",
    name: "Property Training Australia",
    website: "https://propertytraining.com.au",
    state: "Multi",
    type: "Private",
    price: 1450,
    mdpa_score: 89,
    status: "active",
    phone: null,
    email: null,
    rto_code: "91010",
    operational_pattern: "Registry Disclosure Pending",
  },
  {
    id: "4",
    name: "Real Estate Training Academy",
    website: "https://retac.com.au",
    state: "Multi",
    type: "Private",
    price: 1550,
    mdpa_score: 88,
    status: "active",
    phone: null,
    email: "info@retac.com.au",
    rto_code: "",
  },
  {
    id: "5",
    name: "REIQ Training",
    website: "https://www.reiq.com",
    state: "QLD",
    type: "Industry Body",
    price: 2400,
    mdpa_score: 86,
    status: "active",
    phone: "(07) 3249 7373",
    email: "training@reiq.com.au",
    rto_code: "31240",
  },
  {
    id: "6",
    name: "NREL",
    website: "https://nrel.edu.au",
    state: "QLD",
    type: "Private",
    price: 1350,
    mdpa_score: 86,
    status: "active",
    phone: "07 3053 4011",
    email: "info@nrel.edu.au",
    rto_code: "32228",
  },
  {
    id: "7",
    name: "Monarch Institute",
    website: "https://www.monarch.edu.au",
    state: "NSW",
    type: "Private College",
    price: 1695,
    mdpa_score: 85,
    status: "active",
    phone: "1300 738 955",
    email: "tessa.tierney@up.education",
    rto_code: "22530",
  },
  {
    id: "8",
    name: "Entry Education",
    website: "https://www.entryeducation.edu.au",
    state: "NT",
    type: "Private",
    price: 1500,
    mdpa_score: 85,
    status: "active",
    phone: "1300 799 447",
    email: "reception@entryeducation.com.au",
    rto_code: "52174",
  },
  {
    id: "9",
    name: "Real Estate Institute of Victoria",
    website: "https://www.reiv.com.au",
    state: "VIC",
    type: "Industry Body",
    price: 2750,
    mdpa_score: 81,
    status: "active",
    phone: "(03) 9205 6666",
    email: "training@reiv.com.au",
    rto_code: "21180",
  },
  {
    id: "10",
    name: "TAFE Western Australia",
    website: "https://www.northmetrotafe.wa.edu.au",
    state: "WA",
    type: "Public TAFE",
    price: 1750,
    mdpa_score: 77,
    status: "active",
    phone: null,
    email: null,
    rto_code: "",
  },
  {
    id: "11",
    name: "REIWA Training",
    website: "https://reiwa.com.au",
    state: "WA",
    type: "Industry Body",
    price: 2200,
    mdpa_score: 77,
    status: "active",
    phone: "(08) 9380 8222",
    email: "training@reiwa.com.au",
    rto_code: "52787",
  },
  {
    id: "12",
    name: "Validum Institute",
    website: "https://www.validum.edu.au",
    state: "VIC",
    type: "Private",
    price: 1650,
    mdpa_score: 76,
    status: "active",
    phone: null,
    email: "nox@opskill.com.au",
    rto_code: "41107",
  },
  {
    id: "13",
    name: "Think Real Estate",
    website: "https://thinkrealestate.net.au",
    state: "QLD",
    type: "Private",
    price: 1400,
    mdpa_score: 76,
    status: "error",
    phone: null,
    email: "admin@misslollys.com.au",
    rto_code: "32498",
  },
  {
    id: "14",
    name: "CPP41419 Online",
    website: "https://cpp41419.com.au",
    state: "Multi",
    type: "Private",
    price: 1350,
    mdpa_score: 76,
    status: "active",
    phone: null,
    email: null,
    rto_code: "",
  },
  {
    id: "15",
    name: "TAFE NSW",
    website: "https://www.tafensw.edu.au",
    state: "NSW",
    type: "Public TAFE",
    price: 1850,
    mdpa_score: 74,
    status: "active",
    phone: "131 601",
    email: "info@tafensw.edu.au",
    rto_code: "90003",
  },
  {
    id: "16",
    name: "TAFE Queensland",
    website: "https://tafeqld.edu.au",
    state: "QLD",
    type: "Public TAFE",
    price: 1450,
    mdpa_score: 74,
    status: "active",
    phone: "1300 308 233",
    email: "Brent.kinnane@tafeqld.edu.au",
    rto_code: "0275",
  },
  {
    id: "17",
    name: "Western Sydney Institute",
    website: "https://www.wsi.tafensw.edu.au",
    state: "NSW",
    type: "TAFE Campus",
    price: 1750,
    mdpa_score: 74,
    status: "active",
    phone: null,
    email: null,
    rto_code: "",
  },
  {
    id: "18",
    name: "TAFE Victoria",
    website: "https://www.tafe.vic.gov.au",
    state: "VIC",
    type: "Public TAFE",
    price: 1650,
    mdpa_score: 73,
    status: "active",
    phone: null,
    email: null,
    rto_code: "",
  },
  {
    id: "19",
    name: "Ray White Institute",
    website: "https://www.raywhite.com",
    state: "Multi",
    type: "Franchise",
    price: 1900,
    mdpa_score: 73,
    status: "active",
    phone: "1300 729 943",
    email: "institute@raywhite.com",
    rto_code: "45731",
  },
  {
    id: "20",
    name: "TAFE SA",
    website: "https://www.tafesa.edu.au",
    state: "SA",
    type: "Public TAFE",
    price: 1600,
    mdpa_score: 72,
    status: "active",
    phone: "(08) 8207 8101",
    email: "TAFESARegistrations@tafesa.edu.au",
    rto_code: "41026",
  },
  {
    id: "21",
    name: "Holmesglen Institute",
    website: "https://holmesglen.edu.au",
    state: "VIC",
    type: "Public TAFE",
    price: 1700,
    mdpa_score: 71,
    status: "active",
    phone: "(03) 9564 1555",
    email: "info@holmesglen.edu.au",
    rto_code: "0416",
  },
  {
    id: "22",
    name: "REISA Training",
    website: "https://www.reisa.com.au",
    state: "SA",
    type: "Industry Body",
    price: 2100,
    mdpa_score: 70,
    status: "active",
    phone: "(08) 8366 4300",
    email: "training@reisa.com.au",
    rto_code: "40548",
  },
  {
    id: "23",
    name: "ACOP",
    website: "https://acop.edu.au",
    state: "Multi",
    type: "Private",
    price: 1400,
    mdpa_score: 68,
    status: "active",
    phone: "1300 884 810",
    email: "rosys@acop.edu.au",
    rto_code: "91513",
  },
  {
    id: "24",
    name: "CIT Canberra Institute",
    website: "https://cit.edu.au",
    state: "ACT",
    type: "Public TAFE",
    price: 1600,
    mdpa_score: 66,
    status: "active",
    phone: "(02) 6207 3107",
    email: "CITOfficeoftheChiefExecutive@cit.edu.au",
    rto_code: "0101",
  },
  {
    id: "25",
    name: "Australian Training Solutions",
    website: "https://australiantrainingsolutions.com.au",
    state: "NSW",
    type: "Private",
    price: 1450,
    mdpa_score: 65,
    status: "active",
    phone: null,
    email: null,
    rto_code: "",
  },
  {
    id: "26",
    name: "Southern Cross Education",
    website: "https://www.scei.edu.au",
    state: "Multi",
    type: "Private",
    price: 1600,
    mdpa_score: 64,
    status: "active",
    phone: "(03) 9602 4110",
    email: "info@scei.edu.au",
    rto_code: "41253",
  },
  {
    id: "27",
    name: "TAFE Tasmania",
    website: "https://www.tastafe.tas.edu.au",
    state: "TAS",
    type: "Public TAFE",
    price: 1600,
    mdpa_score: 61,
    status: "active",
    phone: "(03) 6165 5671",
    email: "ceo@tafe.tas.edu.au",
    rto_code: "60142",
  },
  {
    id: "28",
    name: "Harcourts Academy",
    website: "https://harcourts.com.au",
    state: "Multi",
    type: "Franchise",
    price: 1800,
    mdpa_score: 57,
    status: "active",
    phone: "1300 654 045",
    email: "academy@harcourts.com.au",
    rto_code: "31958",
  },
  {
    id: "29",
    name: "Box Hill Institute",
    website: "https://www.boxhill.edu.au",
    state: "VIC",
    type: "Public",
    price: 1700,
    mdpa_score: 56,
    status: "active",
    phone: "(03) 9286 9267",
    email: "grant.radford@boxhill.edu.au",
    rto_code: "4687",
  },
  {
    id: "30",
    name: "Chisholm Institute",
    website: "https://www.chisholm.edu.au",
    state: "VIC",
    type: "Public TAFE",
    price: 1650,
    mdpa_score: 54,
    status: "active",
    phone: "1300 244 746",
    email: "stephen.varty@chisholm.edu.au",
    rto_code: "0260",
  },
  {
    id: "31",
    name: "Australian College of Real Estate",
    website: "https://www.acre.edu.au",
    state: "NSW",
    type: "Private College",
    price: 2200,
    mdpa_score: 50,
    status: "error",
    phone: null,
    email: null,
    rto_code: "",
  },
  {
    id: "32",
    name: "Melbourne Institute of Business",
    website: "https://www.mibt.vic.edu.au",
    state: "VIC",
    type: "Private College",
    price: 2100,
    mdpa_score: 50,
    status: "error",
    phone: null,
    email: null,
    rto_code: "",
  },
  {
    id: "33",
    name: "Gold Coast Institute",
    website: "https://www.goldcoast.tafe.qld.gov.au",
    state: "QLD",
    type: "Private College",
    price: 1890,
    mdpa_score: 50,
    status: "error",
    phone: null,
    email: null,
    rto_code: "",
  },
  {
    id: "34",
    name: "Complete Property Training",
    website: "https://completepropertytraining.com.au",
    state: "QLD",
    type: "Private",
    price: 1500,
    mdpa_score: 50,
    status: "error",
    phone: null,
    email: null,
    rto_code: "32143",
  },
  {
    id: "35",
    name: "Charles Darwin University",
    website: "https://www.cdu.edu.au",
    state: "NT",
    type: "University",
    price: 1800,
    mdpa_score: 50,
    status: "error",
    phone: null,
    email: null,
    rto_code: "",
  },
  {
    id: "36",
    name: "National Training Institute",
    website: "https://nti.edu.au",
    state: "NSW",
    type: "Private",
    price: 1500,
    mdpa_score: 50,
    status: "error",
    phone: null,
    email: null,
    rto_code: "",
  },
  {
    id: "37",
    name: "Plenty Training",
    website: "https://plentytraining.edu.au",
    state: "VIC",
    type: "Private",
    price: 1550,
    mdpa_score: 50,
    status: "error",
    phone: null,
    email: null,
    rto_code: "",
  },
  {
    id: "38",
    name: "Real Estate Academy Australia",
    website: "https://realestateacademy.com.au",
    state: "Multi",
    type: "Private",
    price: 1500,
    mdpa_score: 50,
    status: "error",
    phone: null,
    email: null,
    rto_code: "",
  },
  {
    id: "39",
    name: "Real Estate Institute NSW",
    website: "https://www.reinsw.com.au",
    state: "NSW",
    type: "Industry Body",
    price: 2850,
    mdpa_score: 41,
    status: "active",
    phone: "(02) 9264 2343",
    email: "education@reinsw.com.au",
    rto_code: "90272",
  },
  {
    id: "40",
    name: "Southern Solutions Training",
    website: "https://ssts.edu.au",
    state: "Multi",
    type: "Private",
    price: 1350,
    mdpa_score: 34,
    status: "active",
    phone: "1300 656 321",
    email: "info@ssts.edu.au",
    rto_code: "21595",
  },
  {
    id: "41",
    name: "Courses Australia",
    website: "https://courses.com.au",
    state: "Multi",
    type: "Private",
    price: null,
    mdpa_score: 45,
    status: "active",
    phone: null,
    email: null,
    rto_code: "",
  },
  {
    id: "42",
    name: "Salesmasters",
    website: "https://thesalesmasters.com.au",
    state: "SA",
    type: "Private",
    price: null,
    mdpa_score: 20,
    status: "error",
    phone: null,
    email: null,
    rto_code: "",
  },
  {
    id: "43",
    name: "Neuro Coaching Academy",
    website: "https://theneurocoaching.academy",
    state: "National",
    type: "Institute",
    price: null,
    mdpa_score: 15,
    status: "error",
    phone: null,
    email: null,
    rto_code: "",
  },
  {
    id: "44",
    name: "QLD Skills Gateway",
    website: "https://skillsgateway.training.qld.gov.au",
    state: "QLD",
    type: "Government",
    price: null,
    mdpa_score: 72,
    status: "active",
    phone: "1800 773 048",
    email: null,
    rto_code: "",
  },
  {
    id: "45",
    name: "SIIT NSW",
    website: "https://siit.nsw.edu.au",
    state: "NSW",
    type: "Institute",
    price: null,
    mdpa_score: 30,
    status: "error",
    phone: null,
    email: null,
    rto_code: "",
  },
  {
    id: "46",
    name: "RETS",
    website: "https://rets.com.au",
    state: "National",
    type: "Private",
    price: null,
    mdpa_score: 40,
    status: "error",
    phone: null,
    email: null,
    rto_code: "",
  },
  {
    id: "47",
    name: "REIWA Members",
    website: "https://members.reiwa.com.au",
    state: "WA",
    type: "Industry Body",
    price: null,
    mdpa_score: 75,
    status: "active",
    phone: "(08) 9380 8222",
    email: "training@reiwa.com.au",
    rto_code: "52787",
  },
  {
    id: "48",
    name: "Harcourts Training Centre",
    website: "https://realestatetrainingcentre.com",
    state: "NT",
    type: "Franchise",
    price: null,
    mdpa_score: 25,
    status: "error",
    phone: null,
    email: null,
    rto_code: "",
  },
  {
    id: "49",
    name: "Real Estate Training AU",
    website: "https://realestatetraining.com.au",
    state: "National",
    type: "Private",
    price: null,
    mdpa_score: 55,
    status: "active",
    phone: null,
    email: null,
    rto_code: "",
  },
  {
    id: "50",
    name: "REAA",
    website: "https://reaa.com.au",
    state: "National",
    type: "Private",
    price: null,
    mdpa_score: 45,
    status: "error",
    phone: null,
    email: null,
    rto_code: "",
  },
  {
    id: "51",
    name: "Qualify",
    website: "https://qualify.edu.au",
    state: "VIC",
    type: "Institute",
    price: null,
    mdpa_score: 48,
    status: "error",
    phone: null,
    email: null,
    rto_code: "",
  },
  {
    id: "52",
    name: "Original Campus",
    website: "https://originalcampus.edu.au",
    state: "National",
    type: "Institute",
    price: null,
    mdpa_score: 35,
    status: "error",
    phone: null,
    email: null,
    rto_code: "",
  },
  {
    id: "53",
    name: "NTCA",
    website: "https://ntca.edu.au",
    state: "NT",
    type: "Institute",
    price: null,
    mdpa_score: 32,
    status: "error",
    phone: null,
    email: null,
    rto_code: "",
  },
  {
    id: "54",
    name: "National College",
    website: "https://nationalcollege.edu.au",
    state: "SA",
    type: "Institute",
    price: null,
    mdpa_score: 28,
    status: "error",
    phone: null,
    email: null,
    rto_code: "",
  },
  {
    id: "55",
    name: "Living Planit",
    website: "https://livingplanit.com.au",
    state: "National",
    type: "Private",
    price: null,
    mdpa_score: 65,
    status: "active",
    phone: "02 9233 3233",
    email: "enquiries@livingplanit.com.au",
    rto_code: "",
  },
  {
    id: "56",
    name: "Leverage Group",
    website: "https://leveragegroup.com.au",
    state: "National",
    type: "Private",
    price: null,
    mdpa_score: 42,
    status: "error",
    phone: null,
    email: null,
    rto_code: "",
  },
  {
    id: "57",
    name: "Industry Training Alliance",
    website: "https://industrytrainingalliance.com.au",
    state: "National",
    type: "Private",
    price: null,
    mdpa_score: 68,
    status: "active",
    phone: "02 9129 6771",
    email: "info@ita-au.edu.au",
    rto_code: "",
  },
  {
    id: "58",
    name: "Indus Institute",
    website: "https://indusinstitute.edu.au",
    state: "National",
    type: "Institute",
    price: null,
    mdpa_score: 44,
    status: "error",
    phone: null,
    email: null,
    rto_code: "",
  },
  {
    id: "59",
    name: "FWM Group",
    website: "https://fwmgroup.com.au",
    state: "WA",
    type: "Private",
    price: null,
    mdpa_score: 70,
    status: "active",
    phone: "1300 643 484",
    email: "train@fwmgroup.com.au",
    rto_code: "",
  },
  {
    id: "60",
    name: "Harcourts Freshdesk",
    website: "https://trainingcentre.freshdesk.com",
    state: "NT",
    type: "Franchise",
    price: null,
    mdpa_score: 62,
    status: "active",
    phone: "1300 024 401",
    email: null,
    rto_code: "",
  },
  {
    id: "61",
    name: "CCG Community College Gippsland",
    website: "https://ccg.asn.au",
    state: "VIC",
    type: "Institute",
    price: null,
    mdpa_score: 78,
    status: "active",
    phone: "(03) 5622 6000",
    email: null,
    rto_code: "",
  },
  {
    id: "62",
    name: "BCCI",
    website: "https://bcci.edu.au",
    state: "National",
    type: "Institute",
    price: null,
    mdpa_score: 38,
    status: "error",
    phone: null,
    email: null,
    rto_code: "",
  },
  {
    id: "63",
    name: "BBHT",
    website: "https://bbht.com.au",
    state: "QLD",
    type: "Private",
    price: null,
    mdpa_score: 76,
    status: "active",
    phone: "(07) 3117 9722",
    email: "info@abht.com.au",
    rto_code: "",
  },
  {
    id: "64",
    name: "AWS Workplace Skills",
    website: "https://aws.edu.au",
    state: "National",
    type: "Institute",
    price: null,
    mdpa_score: 66,
    status: "active",
    phone: null,
    email: "info@aws.edu.au",
    rto_code: "",
  },
  {
    id: "65",
    name: "ASTC Salesmasters",
    website: "https://astc.edu.au",
    state: "SA",
    type: "Institute",
    price: null,
    mdpa_score: 33,
    status: "error",
    phone: null,
    email: null,
    rto_code: "",
  },
  {
    id: "66",
    name: "Aspire Performance",
    website: "https://aspirept.com.au",
    state: "National",
    type: "Private",
    price: null,
    mdpa_score: 41,
    status: "error",
    phone: null,
    email: null,
    rto_code: "",
  },
  {
    id: "67",
    name: "AIWT",
    website: "https://aiwt.edu.au",
    state: "National",
    type: "Institute",
    price: null,
    mdpa_score: 64,
    status: "active",
    phone: null,
    email: null,
    rto_code: "",
  },
  {
    id: "68",
    name: "SA Skills Gateway",
    website: "https://mytraining.skills.sa.gov.au",
    state: "SA",
    type: "Government",
    price: null,
    mdpa_score: 32,
    status: "error",
    phone: null,
    email: null,
    rto_code: "",
  },
  {
    id: "69",
    name: "Get Your CPP41419",
    website: "https://cpp41419.com.au",
    state: "National",
    type: "Private",
    price: 695,
    mdpa_score: 74,
    status: "active",
    phone: null,
    email: null,
    rto_code: "",
  },
  {
    id: "70",
    name: "REIQ Central",
    website: "https://reiq.com",
    state: "QLD",
    type: "Industry Body",
    price: null,
    mdpa_score: 55,
    status: "error",
    phone: null,
    email: "training@reiq.com.au",
    rto_code: "31240",
  },
]

const seededRandom = (seed: number) => {
  const x = Math.sin(seed++) * 10000
  return x - Math.floor(x)
}

const createGroupHeuristic = (label: string, baseScore: number, seed: number): CategoryGroup => {
  // Generate variance around the base MDPA score for sub-metrics
  const metrics: Metric[] = [
    {
      label: `${label} Fundamental`,
      value: Math.min(100, Math.max(0, baseScore + (seededRandom(seed) * 10 - 5))),
      weight: 3,
    },
    {
      label: `${label} Optimization`,
      value: Math.min(100, Math.max(0, baseScore + (seededRandom(seed + 1) * 20 - 10))),
      weight: 2,
    },
    {
      label: `${label} Reporting`,
      value: Math.min(100, Math.max(0, baseScore + (seededRandom(seed + 2) * 15 - 7.5))),
      weight: 1,
    },
  ]

  const score = Math.round(
    metrics.reduce((acc, m) => acc + m.value * m.weight, 0) / metrics.reduce((acc, m) => acc + m.weight, 0),
  )
  return { label, score, metrics }
}

export const parseData = (): EnrichedProvider[] => {
  return MASTER_REGISTRY.map((p, index) => {
    const base = p.mdpa_score || 50
    const s = index * 53

    const regulatory = createGroupHeuristic("Regulatory Bedrock", base, s)
    const intent = createGroupHeuristic("Intent Fulfillment", base + 2, s + 10)
    const ux = createGroupHeuristic("UX Engineering", base - 3, s + 20)
    const performance = createGroupHeuristic("Performance Stability", base + 5, s + 30)
    const accessibility = createGroupHeuristic("Universal Accessibility", base - 8, s + 40)
    const commercial = createGroupHeuristic("Commercial Integrity", base + 4, s + 50)
    const authority = createGroupHeuristic("Institutional Authority", base + 1, s + 60)

    return {
      id: p.id,
      name: p.name,
      website: p.website,
      website_secondary: p.website_secondary || "",
      state: p.state,
      type: p.type,
      price: p.price,
      mdpa_score: p.mdpa_score,
      status: p.status,
      phone: p.phone,
      email: p.email,
      rto_code: p.rto_code,
      operational_pattern: (p as any).operational_pattern,
      network_id: (p as any).network_id,
      contact_name: p.name.includes("TAFE") ? "Institutional Dean" : "Principal Executive Officer",
      address: `Registry Office, ${p.state}, Australia`,
      audit: {
        groups: { regulatory, intent, ux, performance, accessibility, commercial, authority },
        overall_score: base,
        last_audit: new Date().toISOString().split("T")[0],
        sustainability: {
          attrition_risk: base > 85 ? 0.8 : base > 60 ? 0.6 : 0.9,
          failure_rate: base > 85 ? 0.7 : base > 60 ? 0.5 : 0.85,
          inventory_depth: base > 85 ? "D+" : base > 60 ? "C" : "D",
          wcag_barrier_count: Math.round((100 - base) * 0.8),
          w3c_compliant: base > 95,
        },
      },
    }
  })
}
